### ISSUE TITLE
Incomplete prerequisites list(?) - can compile, but not run QGC on a fresh installed system.

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#10118]
## Expected Behavior
Following build/compilation instructions should give a running app.

## Current Behavior
Unless some prerequisites are fulfilled by other apps, the resulting build can't work,

## Steps to Reproduce:
1.  Install a new Ubuntu 21.04 , 21.10  ... or  (probably  any other recent years debian based distro)
2.  follow build instructions - make the project (which will build just fine)
3.  observe that you can't run it (segfault)
4.  observe that the build itself, WILL run fine on other computers with the same distro, - it is only "missing" something on the one it built on.

I can provide a VMWare workstation image for you to test, if you like. (everything set up)

## System Information
I have used: 
sudo apt install speech-dispatcher libudev-dev libsdl2-dev patchelf make g++ curl git
(a few more apps that required by the build information, but apparently not enough)

- Operating System: verified on Ubuntu 21.04 and 21.10
- Qt 5.15.2
(it does build fine - does not run on the system it builds on, but runs on other, with more packages.)

## Additional information UNRELATED to the fact that the app does not run on the computer it's built on:
1: This information: https://docs.qgroundcontrol.com/master/en/getting_started/download_and_install.html#ubuntu
- does not produce a working gstreamer environment, resulting in ```https://docs.qgroundcontrol.com/master/en/getting_started/download_and_install.html#ubuntu```
2: the system does run older .appimages fine, but is missing something to run it's own build.

## Log Files and Screenshots
this is how it fails on a fresh installed  Ubuntu 21.10  - it's the same for physical computers as in VMware

The wayland error is just wrong, it also shows on systems where QGC runs fine and switching to Xorg does not fix anything.

 ```

:~/qgroundcontrol/build/staging$ gdb ./QGroundControl 
GNU gdb (Ubuntu 11.1-0ubuntu2) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./QGroundControl...
(gdb) run
Starting program: /home/andre/qgroundcontrol/build/staging/QGroundControl 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.


Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737193867392) at pthread_kill.c:44
44	pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737193867392) at pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737193867392) at pthread_kill.c:80
#2  __GI___pthread_kill (threadid=140737193867392, signo=signo@entry=6) at pthread_kill.c:91
#3  0x00007ffff2174476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff215a7b7 in __GI_abort () at abort.c:79
#5  0x000055555591152f in msgHandler (type=QtFatalMsg, context=..., msg=...)
    at /home/andre/qgroundcontrol/src/QmlControls/AppMessages.cc:41
#6  0x00007ffff2716fe0 in qt_message(QtMsgType, QMessageLogContext const&, char const*, __va_list_tag*) ()
   from /home/andre/qgroundcontrol/build/staging/Qt/libs/libQt5Core.so.5
#7  0x00007ffff26ff9a4 in QMessageLogger::fatal(char const*, ...) const ()
   from /home/andre/qgroundcontrol/build/staging/Qt/libs/libQt5Core.so.5
#8  0x00007ffff4867fa0 in QGuiApplicationPrivate::createPlatformIntegration() ()
   from /home/andre/qgroundcontrol/build/staging/Qt/libs/libQt5Gui.so.5
#9  0x00007ffff48682ad in QGuiApplicationPrivate::createEventDispatcher() ()
   from /home/andre/qgroundcontrol/build/staging/Qt/libs/libQt5Gui.so.5
#10 0x00007ffff2911fe3 in QCoreApplicationPrivate::init() ()
   from /home/andre/qgroundcontrol/build/staging/Qt/libs/libQt5Core.so.5
#11 0x00007ffff486accc in QGuiApplicationPrivate::init() ()
   from /home/andre/qgroundcontrol/build/staging/Qt/libs/libQt5Gui.so.5
#12 0x00007ffff5542aa9 in QApplicationPrivate::init() ()
   from /home/andre/qgroundcontrol/build/staging/Qt/libs/libQt5Widgets.so.5
#13 0x00005555558ca3c4 in QGCApplication::QGCApplication (this=0x55555769f1e0, argc=@0x7fffffffdd9c: 1, argv=0x7fffffffdfc8, 
    unitTesting=false) at /home/andre/qgroundcontrol/src/QGCApplication.cc:188
#14 0x0000555555a3bcff in main (argc=1, argv=0x7fffffffdfc8) at /home/andre/qgroundcontrol/src/main.cc:369

```

**Comment by AndKe** [comment]
Please update prerequisites with the packages "libxcb*-dev" 
Doing so makes QGC run.
