### ISSUE TITLE
AppImage crashes on Fedora 27

### ISSUE THREAD

**Issue by julianoes** [mavlink/qgroundcontrol#6081]
Trying to start the AppImage on Fedora, I get a crash just after the window appears.

The version is from:
https://s3-us-west-2.amazonaws.com/qgroundcontrol/latest/QGroundControl.AppImage
`e3d3bd1d04a21053fe5ff870275af1e4  QGroundControl.AppImage`

Running the commands in `AppRun` one by one and then debugging using valgrind gives:

```
valgrind "${HERE}/QGroundControl"
==16262== Memcheck, a memory error detector
==16262== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==16262== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==16262== Command: /mnt/appimage/QGroundControl
==16262== 
Settings location "/home/julianoes/.config/QGroundControl.org/QGroundControl.ini" Is writable?: true
Filter rules "qt.network.ssl.warning=false\n*Log.debug=false\n"
Failed to set Geoclue positioning requirements. Geoclue error: org.qtproject.QtDBus.Error.InvalidObjectPath
MAVLinkLogManagerLog: MAVLink logs directory: "/home/julianoes/Documents/QGroundControl/Logs"
Map Cache in: "/home/julianoes/.cache/QGCMapCache300" / "qgcMapCache.db"
qml: 0.02962962962962963
qml: _activeVehicle(0) _vehicleArmed(0) guidedModeSupported(0) _vehicleFlying(0) _vehicleInRTLMode(0) pauseVehicleSupported(0) _vehiclePaused(0) _flightMode()
qml: _activeVehicle(0) _vehicleArmed(0) guidedModeSupported(0) _vehicleFlying(0) _vehicleInRTLMode(0) pauseVehicleSupported(0) _vehiclePaused(0) _flightMode()
==16262== Use of uninitialised value of size 8
==16262==    at 0x4595DE: __base_ctor  (qcolor.h:281)
==16262==    by 0x4595DE: thumbJoystick (QGCMapPalette.h:57)
==16262==    by 0x4595DE: QGCMapPalette::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (moc_QGCMapPalette.cpp:121)
==16262==    by 0x6DA17A: QGCMapPalette::qt_metacall(QMetaObject::Call, int, void**) (moc_QGCMapPalette.cpp:173)
==16262==    by 0x8E5CB92: ??? (in /mnt/appimage/Qt/libs/libQt5Qml.so.5)
==16262==    by 0x8E5EC7C: QV4::QQmlValueTypeWrapper::write(QObject*, int) const (in /mnt/appimage/Qt/libs/libQt5Qml.so.5)
==16262==    by 0x8E57859: QQmlBinding::write(QQmlPropertyData const&, QV4::Value const&, bool, QFlags<QQmlPropertyPrivate::WriteFlag>) (in /mnt/appimage/Qt/libs/libQt5Qml.so.5)
==16262==    by 0x8E58847: QQmlBinding::update(QFlags<QQmlPropertyPrivate::WriteFlag>) (in /mnt/appimage/Qt/libs/libQt5Qml.so.5)
==16262==    by 0x8E61CA6: ??? (in /mnt/appimage/Qt/libs/libQt5Qml.so.5)
==16262==    by 0x8DF5399: ??? (in /mnt/appimage/Qt/libs/libQt5Qml.so.5)
==16262==    by 0x8DF5DE1: QQmlEnginePrivate::incubate(QQmlIncubator&, QQmlContextData*) (in /mnt/appimage/Qt/libs/libQt5Qml.so.5)
==16262==    by 0x8DF0D25: QQmlComponent::create(QQmlIncubator&, QQmlContext*, QQmlContext*) (in /mnt/appimage/Qt/libs/libQt5Qml.so.5)
==16262==    by 0x6E2A529: ??? (in /mnt/appimage/Qt/libs/libQt5Quick.so.5)
==16262==    by 0x6E2A6A7: ??? (in /mnt/appimage/Qt/libs/libQt5Quick.so.5)
==16262== 
==16262== Conditional jump or move depends on uninitialised value(s)
==16262==    at 0x459555: setLightColors (QGCMapPalette.cc:28)
==16262==    by 0x459555: QGCMapPalette::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (moc_QGCMapPalette.cpp:129)
==16262==    by 0x6DA17A: QGCMapPalette::qt_metacall(QMetaObject::Call, int, void**) (moc_QGCMapPalette.cpp:173)
==16262==    by 0x8DEE201: QQmlPropertyPrivate::write(QObject*, QQmlPropertyData const&, QVariant const&, QQmlContextData*, QFlags<QQmlPropertyPrivate::WriteFlag>) (in /mnt/appimage/Qt/libs/libQt5Qml.so.5)
==16262==    by 0x8DEF672: QQmlPropertyPrivate::writeValueProperty(QObject*, QQmlPropertyData const&, QVariant const&, QQmlContextData*, QFlags<QQmlPropertyPrivate::WriteFlag>) (in /mnt/appimage/Qt/libs/libQt5Qml.so.5)
==16262==    by 0x8E56E0F: QQmlBinding::write(QQmlPropertyData const&, QV4::Value const&, bool, QFlags<QQmlPropertyPrivate::WriteFlag>) (in /mnt/appimage/Qt/libs/libQt5Qml.so.5)
==16262==    by 0x8E58847: QQmlBinding::update(QFlags<QQmlPropertyPrivate::WriteFlag>) (in /mnt/appimage/Qt/libs/libQt5Qml.so.5)
==16262==    by 0x8E61CA6: ??? (in /mnt/appimage/Qt/libs/libQt5Qml.so.5)
==16262==    by 0x8DF5399: ??? (in /mnt/appimage/Qt/libs/libQt5Qml.so.5)
==16262==    by 0x8DF5DE1: QQmlEnginePrivate::incubate(QQmlIncubator&, QQmlContextData*) (in /mnt/appimage/Qt/libs/libQt5Qml.so.5)
==16262==    by 0x8DF0D25: QQmlComponent::create(QQmlIncubator&, QQmlContext*, QQmlContext*) (in /mnt/appimage/Qt/libs/libQt5Qml.so.5)
==16262==    by 0x6E2A529: ??? (in /mnt/appimage/Qt/libs/libQt5Quick.so.5)
==16262==    by 0x6E2A6A7: ??? (in /mnt/appimage/Qt/libs/libQt5Quick.so.5)
==16262== 
qml: 34.5 64
qml: _activeVehicle(0) _vehicleArmed(0) guidedModeSupported(0) _vehicleFlying(0) _vehicleInRTLMode(0) pauseVehicleSupported(0) _vehiclePaused(0) _flightMode()
==16262== Warning: noted but unhandled ioctl 0x6458 with no size/direction hints.
==16262==    This could cause spurious value errors to appear.
==16262==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
Orphaned log file count 0
==16262== Invalid read of size 8
==16262==    at 0x928F49F: ??? (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x92901A3: ??? (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x927CEC4: QSslCertificate::fromData(QByteArray const&, QSsl::EncodingFormat) (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x927EDD1: QSslCertificate::fromPath(QString const&, QSsl::EncodingFormat, QRegExp::PatternSyntax) (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x9299262: ??? (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x92996B3: ??? (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x927CDF4: QSslCertificate::QSslCertificate(QByteArray const&, QSsl::EncodingFormat) (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x927FBE8: QSslConfiguration::QSslConfiguration() (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x9218289: ??? (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x9220281: ??? (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x91FD91F: QNetworkAccessManager::createRequest(QNetworkAccessManager::Operation, QNetworkRequest const&, QIODevice*) (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x91FADF3: QNetworkAccessManager::get(QNetworkRequest const&) (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==  Address 0x1e08b480 is 8 bytes after a block of size 24 alloc'd
==16262==    at 0x4C2FB6B: malloc (vg_replace_malloc.c:299)
==16262==    by 0x30570DF8: CRYPTO_zalloc (in /usr/lib64/libcrypto.so.1.1.0g)
==16262==    by 0x3049812C: ASN1_STRING_type_new (in /usr/lib64/libcrypto.so.1.1.0g)
==16262==    by 0x30490D24: ??? (in /usr/lib64/libcrypto.so.1.1.0g)
==16262==    by 0x3049FB3F: ??? (in /usr/lib64/libcrypto.so.1.1.0g)
==16262==    by 0x304A05C9: ??? (in /usr/lib64/libcrypto.so.1.1.0g)
==16262==    by 0x304A0B34: ??? (in /usr/lib64/libcrypto.so.1.1.0g)
==16262==    by 0x304A0DA5: ??? (in /usr/lib64/libcrypto.so.1.1.0g)
==16262==    by 0x304A04AC: ??? (in /usr/lib64/libcrypto.so.1.1.0g)
==16262==    by 0x304A0B34: ??? (in /usr/lib64/libcrypto.so.1.1.0g)
==16262==    by 0x304A0D4F: ??? (in /usr/lib64/libcrypto.so.1.1.0g)
==16262==    by 0x304A04AC: ??? (in /usr/lib64/libcrypto.so.1.1.0g)
==16262== 
==16262== Invalid read of size 8
==16262==    at 0x928F4A3: ??? (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x92901A3: ??? (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x927CEC4: QSslCertificate::fromData(QByteArray const&, QSsl::EncodingFormat) (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x927EDD1: QSslCertificate::fromPath(QString const&, QSsl::EncodingFormat, QRegExp::PatternSyntax) (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x9299262: ??? (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x92996B3: ??? (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x927CDF4: QSslCertificate::QSslCertificate(QByteArray const&, QSsl::EncodingFormat) (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x927FBE8: QSslConfiguration::QSslConfiguration() (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x9218289: ??? (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x9220281: ??? (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x91FD91F: QNetworkAccessManager::createRequest(QNetworkAccessManager::Operation, QNetworkRequest const&, QIODevice*) (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x91FADF3: QNetworkAccessManager::get(QNetworkRequest const&) (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==16262== 
==16262== 
==16262== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==16262==  Access not within mapped region at address 0x0
==16262==    at 0x928F4A3: ??? (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x92901A3: ??? (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x927CEC4: QSslCertificate::fromData(QByteArray const&, QSsl::EncodingFormat) (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x927EDD1: QSslCertificate::fromPath(QString const&, QSsl::EncodingFormat, QRegExp::PatternSyntax) (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x9299262: ??? (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x92996B3: ??? (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x927CDF4: QSslCertificate::QSslCertificate(QByteArray const&, QSsl::EncodingFormat) (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x927FBE8: QSslConfiguration::QSslConfiguration() (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x9218289: ??? (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x9220281: ??? (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x91FD91F: QNetworkAccessManager::createRequest(QNetworkAccessManager::Operation, QNetworkRequest const&, QIODevice*) (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==    by 0x91FADF3: QNetworkAccessManager::get(QNetworkRequest const&) (in /mnt/appimage/Qt/libs/libQt5Network.so.5)
==16262==  If you believe this happened as a result of a stack
==16262==  overflow in your program's main thread (unlikely but
==16262==  possible), you can try to increase the size of the
==16262==  main thread stack using the --main-stacksize= flag.
==16262==  The main thread stack size used in this run was 8388608.
==16262== 
==16262== Process terminating with default action of signal 11 (SIGSEGV)
==16262==  General Protection Fault
==16262==    at 0x4F97FDC: _dl_catch_error (in /usr/lib64/libc-2.26.so)
==16262==    by 0x4F97756: __libc_dlclose (in /usr/lib64/libc-2.26.so)
==16262==    by 0x4FCA044: free_mem (in /usr/lib64/libc-2.26.so)
==16262==    by 0x4FC9C41: __libc_freeres (in /usr/lib64/libc-2.26.so)
==16262==    by 0x4A2A6DB: _vgnU_freeres (vg_preloaded.c:77)
==16262==    by 0x9EE491F: ??? (in /mnt/appimage/Qt/libs/libQt5Core.so.5)
==16262==    by 0x200: ???
==16262==    by 0x2: ???
==16262==    by 0x1FFEFFEA0F: ???
==16262==    by 0x1FFEFFE91F: ???
==16262==    by 0x1FFEFFE90F: ???
==16262==    by 0x1FFEFFE8FF: ???
==16262== 
==16262== HEAP SUMMARY:
==16262==     in use at exit: 75,596,606 bytes in 214,822 blocks
==16262==   total heap usage: 1,973,329 allocs, 1,758,507 frees, 334,244,687 bytes allocated
==16262== 
==16262== LEAK SUMMARY:
==16262==    definitely lost: 6,152 bytes in 238 blocks
==16262==    indirectly lost: 6,103 bytes in 144 blocks
==16262==      possibly lost: 50,037,828 bytes in 26,446 blocks
==16262==    still reachable: 25,472,171 bytes in 187,731 blocks
==16262==                       of which reachable via heuristic:
==16262==                         length64           : 208,624 bytes in 193 blocks
==16262==                         newarray           : 641,328 bytes in 751 blocks
==16262==                         multipleinheritance: 66,984 bytes in 146 blocks
==16262==         suppressed: 0 bytes in 0 blocks
==16262== Rerun with --leak-check=full to see details of leaked memory
==16262== 
==16262== For counts of detected and suppressed errors, rerun with: -v
==16262== Use --track-origins=yes to see where uninitialised values come from
==16262== ERROR SUMMARY: 13 errors from 4 contexts (suppressed: 0 from 0)
[1]    16262 segmentation fault (core dumped)  valgrind "${HERE}/QGroundControl"
```

And using gdb:
```
gdb "${HERE}/QGroundControl"     
GNU gdb (GDB) Fedora 8.0.1-35.fc27
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /mnt/appimage/QGroundControl...done.
(gdb) r
Starting program: /mnt/appimage/QGroundControl 
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.26-24.fc27.x86_64
Missing separate debuginfo for /mnt/appimage/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/3c/d40ddb22f288a94bbf0792c64a1c028fa510f3.debug
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe0155700 (LWP 17040)]
Settings location "/home/julianoes/.config/QGroundControl.org/QGroundControl.ini" Is writable?: true
Filter rules "qt.network.ssl.warning=false\n*Log.debug=false\n"
[New Thread 0x7fffdf30f700 (LWP 17041)]
[New Thread 0x7fffde834700 (LWP 17043)]
Failed to set Geoclue positioning requirements. Geoclue error: org.qtproject.QtDBus.Error.InvalidObjectPath
MAVLinkLogManagerLog: MAVLink logs directory: "/home/julianoes/Documents/QGroundControl/Logs"
Map Cache in: "/home/julianoes/.cache/QGCMapCache300" / "qgcMapCache.db"
[New Thread 0x7fffdde2c700 (LWP 17044)]
[New Thread 0x7fffdd35b700 (LWP 17045)]
[New Thread 0x7fffc7fff700 (LWP 17046)]
[New Thread 0x7fffc5876700 (LWP 17048)]
qml: 0.02962962962962963
qml: _activeVehicle(0) _vehicleArmed(0) guidedModeSupported(0) _vehicleFlying(0) _vehicleInRTLMode(0) pauseVehicleSupported(0) _vehiclePaused(0) _flightMode()
qml: _activeVehicle(0) _vehicleArmed(0) guidedModeSupported(0) _vehicleFlying(0) _vehicleInRTLMode(0) pauseVehicleSupported(0) _vehiclePaused(0) _flightMode()
qml: 34.5 64
qml: _activeVehicle(0) _vehicleArmed(0) guidedModeSupported(0) _vehicleFlying(0) _vehicleInRTLMode(0) pauseVehicleSupported(0) _vehiclePaused(0) _flightMode()
Orphaned log file count 0

Thread 1 "QGroundControl" received signal SIGSEGV, Segmentation fault.
0x00007ffff380a4a3 in ?? () from /mnt/appimage/Qt/libs/libQt5Network.so.5
Missing separate debuginfos, use: dnf debuginfo-install alsa-lib-1.1.5-1.fc27.x86_64 bzip2-libs-1.0.6-24.fc27.x86_64 dbus-libs-1.12.0-1.fc27.x86_64 espeak-1.48.04-12.fc27.x86_64 expat-2.2.5-1.fc27.x86_64 flac-libs-1.3.2-4.fc27.x86_64 fontconfig-2.12.6-4.fc27.x86_64 freetype-2.8-7.fc27.x86_64 glib2-2.54.3-2.fc27.x86_64 gsm-1.0.17-3.fc27.x86_64 gstreamer1-1.12.4-1.fc27.x86_64 gstreamer1-plugins-base-1.12.4-1.fc27.x86_64 libICE-1.0.9-11.fc27.x86_64 libSM-1.2.2-7.fc27.x86_64 libX11-1.6.5-4.fc27.x86_64 libX11-xcb-1.6.5-4.fc27.x86_64 libXScrnSaver-1.2.2-13.fc27.x86_64 libXau-1.0.8-9.fc27.x86_64 libXcursor-1.1.14-10.fc27.x86_64 libXdamage-1.1.4-11.fc27.x86_64 libXext-1.3.3-7.fc27.x86_64 libXfixes-5.0.3-4.fc27.x86_64 libXi-1.7.9-4.fc27.x86_64 libXinerama-1.1.3-9.fc27.x86_64 libXrandr-1.5.1-4.fc27.x86_64 libXrender-0.9.10-4.fc27.x86_64 libXtst-1.2.3-4.fc27.x86_64 libXxf86vm-1.1.4-6.fc27.x86_64 libasyncns-0.8-13.fc27.x86_64 libcap-2.25-7.fc27.x86_64 libdrm-2.4.89-1.fc27.x86_64 libffi-3.1-14.fc27.x86_64 libgcc-7.2.1-2.fc27.x86_64 libgcrypt-1.8.2-1.fc27.x86_64 libglvnd-1.0.0-1.fc27.x86_64 libglvnd-egl-1.0.0-1.fc27.x86_64 libglvnd-glx-1.0.0-1.fc27.x86_64 libgpg-error-1.27-3.fc27.x86_64 libogg-1.3.2-8.fc27.x86_64 libpciaccess-0.13.4-6.fc27.x86_64 libpng-1.6.31-1.fc27.x86_64 libselinux-2.7-3.fc27.x86_64 libsndfile-1.0.28-6.fc27.x86_64 libstdc++-7.2.1-2.fc27.x86_64 libuuid-2.30.2-1.fc27.x86_64 libvorbis-1.3.5-4.fc27.x86_64 libwayland-client-1.14.0-2.fc27.x86_64 libwayland-cursor-1.14.0-2.fc27.x86_64 libxcb-1.12-5.fc27.x86_64 libxkbcommon-0.7.1-5.fc27.x86_64 libxshmfence-1.2-6.fc27.x86_64 lz4-libs-1.8.0-1.fc27.x86_64 mesa-dri-drivers-17.2.4-3.fc27.x86_64 mesa-libGL-17.2.4-3.fc27.x86_64 mesa-libglapi-17.2.4-3.fc27.x86_64 mesa-libwayland-egl-17.2.4-3.fc27.x86_64 nss-mdns-0.10-20.fc27.x86_64 openssl-devel-1.1.0g-1.fc27.x86_64 orc-0.4.28-1.fc27.x86_64 pcre-8.41-4.fc27.x86_64 pcre2-10.30-5.fc27.x86_64 pulseaudio-libs-11.1-7.fc27.x86_64 sssd-client-1.16.0-5.fc27.x86_64 systemd-libs-234-9.fc27.x86_64 tcp_wrappers-libs-7.6-87.fc27.x86_64 xz-libs-5.2.3-4.fc27.x86_64 zlib-1.2.11-4.fc27.x86_64

(gdb) bt
#0  0x00007ffff380a4a3 in  () at /mnt/appimage/Qt/libs/libQt5Network.so.5
#1  0x00007ffff380b1a4 in  () at /mnt/appimage/Qt/libs/libQt5Network.so.5
#2  0x00007ffff37f7ec5 in QSslCertificate::fromData(QByteArray const&, QSsl::EncodingFormat) () at /mnt/appimage/Qt/libs/libQt5Network.so.5
#3  0x00007ffff37f9dd2 in QSslCertificate::fromPath(QString const&, QSsl::EncodingFormat, QRegExp::PatternSyntax) ()
    at /mnt/appimage/Qt/libs/libQt5Network.so.5
#4  0x00007ffff3814263 in  () at /mnt/appimage/Qt/libs/libQt5Network.so.5
#5  0x00007ffff38146b4 in  () at /mnt/appimage/Qt/libs/libQt5Network.so.5
#6  0x00007ffff37f7df5 in QSslCertificate::QSslCertificate(QByteArray const&, QSsl::EncodingFormat) () at /mnt/appimage/Qt/libs/libQt5Network.so.5
#7  0x00007ffff37fabe9 in QSslConfiguration::QSslConfiguration() () at /mnt/appimage/Qt/libs/libQt5Network.so.5
#8  0x00007ffff379328a in  () at /mnt/appimage/Qt/libs/libQt5Network.so.5
#9  0x00007ffff379b282 in  () at /mnt/appimage/Qt/libs/libQt5Network.so.5
#10 0x00007ffff3778920 in QNetworkAccessManager::createRequest(QNetworkAccessManager::Operation, QNetworkRequest const&, QIODevice*) ()
    at /mnt/appimage/Qt/libs/libQt5Network.so.5
#11 0x00007ffff3775df4 in QNetworkAccessManager::get(QNetworkRequest const&) () at /mnt/appimage/Qt/libs/libQt5Network.so.5
#12 0x00000000005040cb in QGeoTiledMapReplyQGC::cacheError(QGCMapTask::TaskType, QString) (this=0x1564e10, type=<optimized out>)
    at /home/travis/build/mavlink/qgroundcontrol/src/QtLocationPlugin/QGeoMapReplyQGC.cpp:165
#13 0x0000000000565b23 in QtPrivate::FunctorCall::call (arg=<optimized out>, o=<optimized out>, f=<optimized out>)
    at ../Qt5.7-linux/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h:141
#14 0x0000000000565b23 in QtPrivate::FunctionPointer::call (f=<optimized out>, o=<optimized out>, arg=<optimized out>)
    at ../Qt5.7-linux/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h:160
#15 0x0000000000565b23 in QtPrivate::QSlotObject<void (QGeoTiledMapReplyQGC::*)(QGCMapTask::TaskType, QString), QtPrivate::List<QGCMapTask::TaskType, QString>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) [clone .local.5050] (which=<optimized out>, this_=<optimized out>, r=<optimized out>, a=<optimized out>, ret=<optimized out>, ret=<optimized out>, a=<optimized out>, this_=<optimized out>)
    at ../Qt5.7-linux/5.7/gcc_64/include/QtCore/qobject_impl.h:120
#16 0x00007ffff2bfccaa in QObject::event(QEvent*) () at /mnt/appimage/Qt/libs/libQt5Core.so.5
---Type <return> to continue, or q <return> to quit---
#17 0x00007ffff4e98bdc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /mnt/appimage/Qt/libs/libQt5Widgets.so.5
#18 0x00007ffff4e9f8d0 in QApplication::notify(QObject*, QEvent*) () at /mnt/appimage/Qt/libs/libQt5Widgets.so.5
#19 0x00007ffff2bd40b0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /mnt/appimage/Qt/libs/libQt5Core.so.5
#20 0x00007ffff2bd6aeb in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /mnt/appimage/Qt/libs/libQt5Core.so.5
#21 0x00007ffff2c21103 in  () at /mnt/appimage/Qt/libs/libQt5Core.so.5
#22 0x00007ffff651eb77 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#23 0x00007ffff651ef20 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#24 0x00007ffff651efac in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#25 0x00007ffff2c214f7 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /mnt/appimage/Qt/libs/libQt5Core.so.5
#26 0x00007ffff2bd239a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /mnt/appimage/Qt/libs/libQt5Core.so.5
#27 0x00007ffff2bda17d in QCoreApplication::exec() () at /mnt/appimage/Qt/libs/libQt5Core.so.5
#28 0x000000000044201f in main(int, char**) (argc=1, argv=<optimized out>) at /home/travis/build/mavlink/qgroundcontrol/src/main.cc:253

```

**Comment by DonLakeFlyer** [comment]
I think I fixed this. Can you try new daily.? AppImage at least works for me now on Ubuntu 16.04.

**Comment by julianoes** [comment]
Tested latest daily. You're right, it works.
Thanks a lot!

**Comment by DonLakeFlyer** [comment]
Phew!
