### ISSUE TITLE
Android: Large number of crashes from QGCActivity.nativeUpdateAvailableJoysticks

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#7445]
This is being reporting as 100s of crashes on the Google Play store stable build:

Today, 9:58 AM on app version 352000
Samsung Galaxy Note5 (noblelte), Android 7.0
Report 1

java.lang.UnsatisfiedLinkError: 
  at org.mavlink.qgroundcontrol.QGCActivity.nativeUpdateAvailableJoysticks (Native Method)
  at org.mavlink.qgroundcontrol.QGCActivity.access$800 (QGCActivity.java:65)
  at org.mavlink.qgroundcontrol.QGCActivity$3.onReceive (QGCActivity.java:169)
  at android.app.LoadedApk$ReceiverDispatcher$Args.run (LoadedApk.java:1185)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6682)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)

**Comment by DonLakeFlyer** [comment]
@MatejFranceskin It's critical that you look at this one. It's blowing up all over the place on people using Stable build.

**Comment by MatejFranceskin** [comment]
I am looking at it but the problem is that I cannot reproduce it on my devices. It is ok with or without joystick.
Do you have any more information? It could be dependent on Android version.

**Comment by MatejFranceskin** [comment]
When did this problems start? Immediately after it was included in the build or later?
Did we change target SDK version recently?

**Comment by DonLakeFlyer** [comment]
Looks like all over the place:
![Screen Shot 2019-05-16 at 9 41 11 AM](https://user-images.githubusercontent.com/5876851/57871925-621c6e00-77bf-11e9-8b55-6ebdfa720029.png)

Do you have access to Google Play Dev Store? Probably should. Daniel should be able to get it for you. Then you can see crash reports directly.

**Comment by sjd69** [comment]
I've replicated this issue using a Note 8 (Qualcomm) as well as a S9+ (Qualcomm).

In my case it happens when opening QGroundControl with a DJI drone (using RosettaDrone) already connected. Starting QGroundControl prior to connecting the drone resolves the issue seemingly permanently and allows me start and restart QGroundControl freely in any order. Issue will appear again on a fresh install.

```
    --------- beginning of main
2019-05-16 11:41:39.731 12119-12119/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mavlink.qgroundcontrol, PID: 12119
    java.lang.UnsatisfiedLinkError: No implementation found for void org.mavlink.qgroundcontrol.QGCActivity.nativeUpdateAvailableJoysticks() (tried Java_org_mavlink_qgroundcontrol_QGCActivity_nativeUpdateAvailableJoysticks and Java_org_mavlink_qgroundcontrol_QGCActivity_nativeUpdateAvailableJoysticks__)
        at org.mavlink.qgroundcontrol.QGCActivity.nativeUpdateAvailableJoysticks(Native Method)
        at org.mavlink.qgroundcontrol.QGCActivity.access$800(QGCActivity.java:65)
        at org.mavlink.qgroundcontrol.QGCActivity$3.onReceive(QGCActivity.java:169)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52226(LoadedApk.java:1319)
        at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.$m$0(Unknown Source:4)
        at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.run(Unknown Source:0)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6940)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by DonLakeFlyer** [comment]
@sjd69 Can you try the QGC Daily build from the store? I believe that has the fix in it now.

**Comment by sjd69** [comment]
@DonLakeFlyer It appears to fix the issue on both devices.

**Comment by DonLakeFlyer** [comment]
@sjd69 Awesome, thanks so much for testing.

**Comment by DonLakeFlyer** [comment]
This needs to be in Stable branch as well

**Comment by DonLakeFlyer** [comment]
@MatejFranceskin Can you move this to Stable_V3.5.1?
